name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _vest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Debug information
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"

        echo "Current directory: $(pwd)"
        ls -la

    - name: Install dependencies

      run: npm ci --verbose || (echo "npm ci failed" && exit 1)

    - name: Run tests
      run: npm test --verbose || (echo "tests failed" && exit 1) 
